apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: trivy-image
spec:
  image: ghcr.io/jessesuen/trivy:0.69.3
  command:
  - trivy
  - image
  - --image-src=remote
  - --exit-code=1
  - --severity=CRITICAL
  - --disable-telemetry
  - --skip-db-update
  - --skip-java-db-update
  - --scanners=vuln
  - ${{ config.image }}
