apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: custom-steps
spec:
  vars:
  - name: image
    value: ghcr.io/jessesuen/nginx
  - name: repoURL
    value: https://github.com/jessesuen/kargo-custom-steps.git
  - name: branch
    value: main

  steps:
  - uses: compose-output
    as: image
    config:
      image: ${{ imageFrom( vars.image ).Tag }}

  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./src

  - uses: yaml-update
    config:
      path: ./src/env/${{ ctx.stage }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom( vars.image ).Tag }}

  - uses: helm-template
    config:
      path: ./src/charts/app
      releaseName: app
      valuesFiles:
      - ./src/env/${{ ctx.stage }}/values.yaml
      outPath: ./out/manifests.yaml

  - uses: conftest
    config:
      path: ./out
      policyPath: ./src/policy

  - uses: trivy
    config:
      path: ./out

  # - uses: git-commit
  #   as: commit
  #   config:
  #     path: ./src
  #     message: |
  #       Update ${{ ctx.stage }} to ${{ ctx.targetFreight.name }}

  #       K8s Image: ${{ vars.image }}:${{ imageFrom(vars.image).Tag }}
  #       Lambda: ${{ vars.lambda }}:${{ imageFrom(vars.lambda).Tag }}

  #       Terraform Apply:
  #       ${{ task.outputs['tf-apply'].result }}
