apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: hello-world
spec:
  image: busybox:1.37.0
  command:
  - sh
  - -c
  - |
    set -o pipefail
    echo "This is a hello world custom promotion step with outputs"
    echo hello=world >> $KARGO_OUTPUT
    echo foo=bar >> $KARGO_OUTPUT
