apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: custom-steps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: custom-steps-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/jessesuen/kargo-custom-steps.git
