apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: grype
spec:
  image: ghcr.io/jessesuen/grype:0.110.0
  command:
  - grype
  - ${{ config.image }}
  output:
    source:
      type: Stdout
      format: Text
    transform:
      vulnerabilities: 'trim(output) == "" ? [] : split(trim(output), "\n")'
